import { Router } from "express";
import authRoutes from "./auth.routes.js";
import courseRoutes from "./courses.routes.js";
import serviceRoutes from "./services.routes.js";
import eventRoutes from "./events.routes.js";
import paymentRoutes from "./payments.routes.js";
import contactRoutes from "./contact.routes.js";
import contentRoutes from "./content.routes.js";
import adminRoutes from "./admin.routes.js";
import uploadRoutes from "./upload.routes.js";
import certificateRoutes from "./certificates.routes.js";
import serviceRequestRoutes from "./serviceRequests.routes.js";
import materialsRoutes from "./materials.routes.js";
import meRoutes from "./me.routes.js";

const r = Router();
r.use("/auth", authRoutes);
r.use("/courses", courseRoutes);
r.use("/services", serviceRoutes);
r.use("/events", eventRoutes);
r.use("/payments", paymentRoutes);
r.use("/contact", contactRoutes);
r.use("/content", contentRoutes);
r.use("/admin", adminRoutes);
r.use("/uploads", uploadRoutes);
r.use("/certificates", certificateRoutes);
r.use("/service-requests", serviceRequestRoutes);
r.use("/materials", materialsRoutes);
r.use("/me", meRoutes);
export default r;
