/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MeRouteImport } from './routes/me'
import { Route as MyMaterialsRouteImport } from './routes/my-materials'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminMaterialsRouteImport } from './routes/admin.materials'
import { Route as AdminServiceRequestsRouteImport } from './routes/admin.service-requests'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSuperAdminRouteImport } from './routes/admin.super-admin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as BundlesSlugRouteImport } from './routes/bundles.$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as MaterialsIndexRouteImport } from './routes/materials.index'
import { Route as MaterialsSlugRouteImport } from './routes/materials.$slug'
import { Route as MeCoursesRouteImport } from './routes/me.courses'
import { Route as MeOrdersRouteImport } from './routes/me.orders'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MyMaterialsRoute = MyMaterialsRouteImport.update({
  id: '/my-materials',
  path: '/my-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceRequestsRoute = AdminServiceRequestsRouteImport.update({
  id: '/service-requests',
  path: '/service-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuperAdminRoute = AdminSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const BundlesSlugRoute = BundlesSlugRouteImport.update({
  id: '/bundles/$slug',
  path: '/bundles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsSlugRoute = MaterialsSlugRouteImport.update({
  id: '/materials/$slug',
  path: '/materials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MeCoursesRoute = MeCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => MeRoute,
} as any)
const MeOrdersRoute = MeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MeRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/me': typeof MeRouteWithChildren
  '/my-materials': typeof MyMaterialsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/me/courses': typeof MeCoursesRoute
  '/me/orders': typeof MeOrdersRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/me': typeof MeRouteWithChildren
  '/my-materials': typeof MyMaterialsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/me/courses': typeof MeCoursesRoute
  '/me/orders': typeof MeOrdersRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/materials': typeof MaterialsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/me': typeof MeRouteWithChildren
  '/my-materials': typeof MyMaterialsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/me/courses': typeof MeCoursesRoute
  '/me/orders': typeof MeOrdersRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/me'
    | '/my-materials'
    | '/testimonials'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/materials'
    | '/admin/service-requests'
    | '/admin/services'
    | '/admin/super-admin'
    | '/auth/forgot-password'
    | '/bundles/$slug'
    | '/courses/$slug'
    | '/materials/$slug'
    | '/me/courses'
    | '/me/orders'
    | '/services/$slug'
    | '/courses/'
    | '/materials/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/me'
    | '/my-materials'
    | '/testimonials'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/materials'
    | '/admin/service-requests'
    | '/admin/services'
    | '/admin/super-admin'
    | '/auth/forgot-password'
    | '/bundles/$slug'
    | '/courses/$slug'
    | '/materials/$slug'
    | '/me/courses'
    | '/me/orders'
    | '/services/$slug'
    | '/courses'
    | '/materials'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/me'
    | '/my-materials'
    | '/testimonials'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/materials'
    | '/admin/service-requests'
    | '/admin/services'
    | '/admin/super-admin'
    | '/auth/forgot-password'
    | '/bundles/$slug'
    | '/courses/$slug'
    | '/materials/$slug'
    | '/me/courses'
    | '/me/orders'
    | '/services/$slug'
    | '/courses/'
    | '/materials/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  MeRoute: typeof MeRouteWithChildren
  MyMaterialsRoute: typeof MyMaterialsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BundlesSlugRoute: typeof BundlesSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  MaterialsSlugRoute: typeof MaterialsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-materials': {
      id: '/my-materials'
      path: '/my-materials'
      fullPath: '/my-materials'
      preLoaderRoute: typeof MyMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-requests': {
      id: '/admin/service-requests'
      path: '/service-requests'
      fullPath: '/admin/service-requests'
      preLoaderRoute: typeof AdminServiceRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/super-admin': {
      id: '/admin/super-admin'
      path: '/super-admin'
      fullPath: '/admin/super-admin'
      preLoaderRoute: typeof AdminSuperAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/bundles/$slug': {
      id: '/bundles/$slug'
      path: '/bundles/$slug'
      fullPath: '/bundles/$slug'
      preLoaderRoute: typeof BundlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$slug': {
      id: '/materials/$slug'
      path: '/materials/$slug'
      fullPath: '/materials/$slug'
      preLoaderRoute: typeof MaterialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/courses': {
      id: '/me/courses'
      path: '/courses'
      fullPath: '/me/courses'
      preLoaderRoute: typeof MeCoursesRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/orders': {
      id: '/me/orders'
      path: '/orders'
      fullPath: '/me/orders'
      preLoaderRoute: typeof MeOrdersRouteImport
      parentRoute: typeof MeRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminServiceRequestsRoute: typeof AdminServiceRequestsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSuperAdminRoute: typeof AdminSuperAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminServiceRequestsRoute: AdminServiceRequestsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSuperAdminRoute: AdminSuperAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MeRouteChildren {
  MeCoursesRoute: typeof MeCoursesRoute
  MeOrdersRoute: typeof MeOrdersRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeCoursesRoute: MeCoursesRoute,
  MeOrdersRoute: MeOrdersRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  MeRoute: MeRouteWithChildren,
  MyMaterialsRoute: MyMaterialsRoute,
  TestimonialsRoute: TestimonialsRoute,
  BundlesSlugRoute: BundlesSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  MaterialsSlugRoute: MaterialsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
